import { Router, type IRouter } from "express";
import healthRouter from "./health";
import chatRouter from "./chat";
import remindersRouter from "./reminders";
import transcribeRouter from "./transcribe";
import authRouter from "./auth";
import winddownRouter from "./winddown";
import memoryRouter from "./memory";
import messagesRouter from "./messages";
import onboardingRouter from "./onboarding";
import pushRouter from "./push";
import oliviaRouter from "./olivia";
import demoRouter from "./demo";
import legalRouter from "./legal";
import settingsRouter from "./settings";
import contactsRouter from "./contacts";
import listsRouter from "./lists";
import weatherRouter from "./weather";
import medicationsRouter from "./medications";
import billsRouter from "./bills";
import garminRouter from "./garmin";
import adminRouter from "./admin";
import journalRouter from "./journal";
import memoriesRouter from "./memories";
import conversationRouter from "./conversation";
import mydayRouter from "./myday";
import lifeRouter from "./life";
import connectRouter from "./connect";
import ordersRouter from "./orders";
import emailRouter from "./email";
import calendarSmartRouter from "./calendarSmart";
import travelRouter from "./travel";
import ttsRouter from "./tts";
import locationRouter from "./location";
import providersRouter from "./providers";
import peopleRouter from "./people";
import integrationsRouter from "./integrations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(demoRouter);
router.use(authRouter);
router.use(onboardingRouter);
router.use(legalRouter);
router.use(chatRouter);
router.use(remindersRouter);
router.use(transcribeRouter);
router.use(winddownRouter);
router.use(memoryRouter);
router.use(messagesRouter);
router.use(pushRouter);
router.use(oliviaRouter);
router.use(settingsRouter);
router.use(contactsRouter);
router.use(listsRouter);
router.use(weatherRouter);
router.use(medicationsRouter);
router.use(billsRouter);
router.use(garminRouter);
router.use(adminRouter);
router.use(journalRouter);
router.use(memoriesRouter);
router.use(conversationRouter);
router.use(mydayRouter);
router.use(lifeRouter);
router.use(connectRouter);
router.use(ordersRouter);
router.use(emailRouter);
router.use(calendarSmartRouter);
router.use(travelRouter);
router.use(ttsRouter);
router.use(locationRouter);
router.use(providersRouter);
router.use(peopleRouter);
router.use(integrationsRouter);

export default router;
