kind = "web"
previewPath = "/"
title = "Winston"
version = "1.0.0"
id = "artifacts/winston"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20925

[services.development]
run = "pnpm --filter @workspace/winston run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/winston", "run", "build" ]
publicDir = "artifacts/winston/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20925"
BASE_PATH = "/"
